### ISSUE TITLE
Localized errors

### ISSUE THREAD

**Issue by AnandChowdhary** [sindresorhus/is-network-error#1]
In production, we've tracked many "Failed to fetch"-like errors but in different languages. Because of this, [Sentry started translating errors](https://blog.sentry.io/internet-explorer-translations/) for consistency. But unfortunately this means that if you're using an older Edge or IE (no other browser does this AFAIK), the error thrown will be "Failed to Fetch" but in French, for example.

This is the dataset of localized error messages: https://github.com/getsentry/sentry/pull/6709

Does it make sense to add fetch-relevant errors but in various languages in this package too?

**Comment by sindresorhus** [comment]
Fetch is not supported on those browsers.

**Comment by AnandChowdhary** [comment]
Aah you're right, thank you!
