### ISSUE TITLE
TypeError cancelled

### ISSUE THREAD

**Issue by BarryThePenguin** [sindresorhus/is-network-error#4]
It looks like bot Safari 14 and iOS Safari 14 can throw a `TypeError` with a message of `cancelled` when a fetch request is cancelled. Would it make sense to include here?

See also https://github.com/shuding/request-cancellation-test 👀

**Comment by sindresorhus** [comment]
Cancellation is not a network error, so I don't think it makes sense in this package.

**Comment by BarryThePenguin** [comment]
That's fair.. I guess I'm trying to achieve something more specific where I am using `is-network-error` to detect if an error was the result of a network error or not. Due to the multiple ways that different browsers report network errors, it's difficult to determine the cause of a particular network error.

For instance, Chrome appears to use the same error `TypeError: Failed to fetch` for both network errors and fetch requests that have been aborted, either using `AbortSignal` or from the browser itself. So in that instance it's difficult to differentiate them.

In this instance it looks like the error message produced by Safari might distinguish between a network error and aborted fetch request? If that's the case, I'll just handle the `TypeError: cancelled` error myself.

**Comment by sindresorhus** [comment]
> In this instance it looks like the error message produced by Safari might distinguish between a network error and aborted fetch request?

Seems like that, yes.
